# Generated by Django 5.0.6 on 2024-06-22 13:04

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('email_id', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(validators=[django.core.validators.MinLengthValidator(8, 'the file must contain atleast 8 characters0')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
