# Generated by Django 5.0.6 on 2024-06-22 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(8, 'the file must contain atleast 8 characters0'), django.core.validators.RegexValidator('[+-/%]', inverse_match=True, message='should not contains special chanracters')]),
        ),
    ]
